version: "3.9"

services:
  postgres:
    image: postgres:15-alpine
    container_name: paydaybank-postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - paydaybank-network

  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.0
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
    networks:
      - paydaybank-network

  kafka:
    image: confluentinc/cp-kafka:7.4.0
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - paydaybank-network

  mailhog:
    image: mailhog/mailhog
    container_name: mailhog
    ports:
      - "1025:1025"
      - "8025:8025"
    networks:
      - paydaybank-network

  auth-service:
    build: ./auth-service
    container_name: auth-service
    ports:
      - "8085:8085"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/${POSTGRES_DB}
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRATION: ${JWT_EXPIRATION}
      SERVER_PORT: 8085
      USER_SERVICE_URL: http://user-service:8086
    depends_on:
      - postgres
    networks:
      - paydaybank-network

  user-service:
    build: ./user-service
    container_name: user-service
    ports:
      - "8086:8086"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/${POSTGRES_DB}
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
      AUTH_SERVICE_URL: http://auth-service:8085
      SERVER_PORT: 8086
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:29092
      LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_KAFKA: DEBUG
    depends_on:
      - postgres
      - auth-service
      - kafka
    networks:
      - paydaybank-network

  notification-service:
    build: ./notification-service
    container_name: notification-service
    ports:
      - "8087:8087"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/${POSTGRES_DB}
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
      AUTH_SERVICE_URL: http://auth-service:8085
      SERVER_PORT: 8087
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:29092
      MAIL_HOST: mailhog
    depends_on:
      - postgres
      - kafka
    networks:
      - paydaybank-network

  email_confirmation-service:
    build: ./email_confirmation-service
    container_name: email_confirmation-service
    ports:
      - "8088:8088"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/${POSTGRES_DB}
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
      AUTH_SERVICE_URL: http://auth-service:8085
      SERVER_PORT: 8088
    depends_on:
      - postgres
    networks:
      - paydaybank-network

  account-service:
    build: ./account-service
    container_name: account-service
    ports:
      - "8089:8089"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/${POSTGRES_DB}
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
      AUTH_SERVICE_URL: http://auth-service:8085
      SERVER_PORT: 8089
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:29092
      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRATION: ${JWT_EXPIRATION}
    depends_on:
      - postgres
      - kafka
    networks:
      - paydaybank-network

volumes:
  postgres-data:


networks:
  paydaybank-network:
    driver: bridge
