version: "3.9"

services:
  postgres:
    image: postgres:15-alpine
    container_name: paydaybank-postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - paydaybank-network

  auth-service:
    build: ./auth-service
    container_name: auth-service
    ports:
      - "8085:8085"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/${POSTGRES_DB}
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRATION: ${JWT_EXPIRATION}
      SERVER_PORT: 8085
      USER_SERVICE_URL: http://user-service:8086
    depends_on:
      - postgres
    networks:
      - paydaybank-network

  user-service:
    build: ./user-service
    container_name: user-service
    ports:
      - "8086:8086"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/${POSTGRES_DB}
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
      AUTH_SERVICE_URL: http://auth-service:8085
      SERVER_PORT: 8086
    depends_on:
      - postgres
      - auth-service
    networks:
      - paydaybank-network

volumes:
  postgres-data:


networks:
  paydaybank-network:
    driver: bridge
